// @generated by site_engine/export_typescript; do not edit.

export const SITE_BUILD_SCHEMA = "site-build/v2" as const;
export const API_VERSION = 1 as const;
export const PREPARED_PACKAGE_MEDIA_TYPE = "application/vnd.fhir.package.prepared.v3" as const;
export const PREPARED_PACKAGE_FORMAT_VERSION = 3 as const;
export const SITE_OUTPUT_SCHEMA = "site-output/v1" as const;
export const SITE_OUTPUT_MANIFEST_PATH = "site-output.json" as const;
export const RESOLVER_SCHEMA = 3 as const;

export type ProjectRevision = { config: string, fsh: { [key in string]: string }, predefined: { [key in string]: unknown }, siteFiles: { [key in string]: string }, };
export type CompilationDefinitionKind = "fsh-declaration";
export type CompilationDefinition = { kind: CompilationDefinitionKind, path: string, line: number, column: number, };
export type CompilationDiagnosticSeverity = "error" | "warning" | "info";
export type CompilationResource = { filename: string, text: string, resourceType?: string, id?: string, url?: string, definition?: CompilationDefinition, };
export type CompilationDiagnostic = { severity: CompilationDiagnosticSeverity, message: string, file?: string, line?: number, ownerDefinition?: CompilationDefinition, };
export type CompilationOutcome = { resources: Array<CompilationResource>, diagnostics: Array<CompilationDiagnostic>, };
export type TemplateResolution = { satisfied: boolean, chain: Array<string>, missing?: string, };
export type GeneratorKind = "cycle" | "publisher";
export type PrepareResult = { buildId: string, generator: GeneratorKind, siteBuild: ClosedSiteBuild, };
export type PreparedProjectResult = { compiled: CompilationOutcome, site: PrepareResult, events: Array<BuildEvent>, };
export type PackageRequest = { package_id: string, version: string, };
export type RequestedSet = "compile" | "context";
export type MissingReason = { "kind": "not_mounted" } | { "kind": "unresolved_version", requested: string, };
export type MissingPackage = { package_id: string,
/**
 * The concrete version the resolver selected (if it could resolve one), or the
 * raw requested coordinate when it could not (`latest`/`current` with no index).
 */
version: string,
/**
 * Why this package is in `missing`: the exact, host-renderable reason.
 */
reason: MissingReason,
/**
 * The set that referenced it (`compile` or `context`), for the host's UI.
 */
set: RequestedSet, };
export type MutableVersionRequest = { package_id: string, requested: string, resolved_version: string | null, set: RequestedSet, };
export type ResolutionStep = {
/**
 * Schema for the resolver semantics represented by this result. Hosts may
 * persist an exact closure as an optimization, but must discard it when
 * this value changes and must still re-run this resolver before use.
 */
resolver_schema: number,
/**
 * Stock-SUSHI COMPILE load set (non-transitive), in stock load order. Every
 * entry is a concrete `pkg#ver` the compile needs mounted.
 */
compile_set: Array<PackageRequest>,
/**
 * Transitive snapshot/render context closure rooted at the exact compile
 * set and walked over the MOUNTED packages (R4-compat filtered,
 * core-canonicalized), with core first then discovery order.
 */
context_closure: Array<PackageRequest>,
/**
 * Mounted package manifests read while proving `context_closure`, including
 * packages later excluded by compatibility rules. Replaying a cached
 * resolution must mount these witnesses too; the final closure alone is
 * not sufficient to prove that an excluded dependency remains excluded.
 */
resolution_support: Array<PackageRequest>,
/**
 * Packages referenced by either set that are not yet mounted (or whose version
 * could not be resolved). Fetch these, mount, and resolve again.
 */
missing: Array<MissingPackage>,
/**
 * True iff nothing is missing — the mounted set fully satisfies both closures
 * and the host loop has reached its fixpoint.
 */
satisfied: boolean,
/**
 * Every non-concrete version request which influenced this step. A cached
 * closure is not fresh merely because its concrete packages still exist:
 * the host must refresh the candidate universe for these requests before
 * asking Rust to verify the closure again.
 */
mutable_requests: Array<MutableVersionRequest>, };
export type VersionIndex = {
/**
 * package id -> the list of available version strings (order irrelevant; the
 * resolver sorts).
 */
versions: { [key in string]: Array<string> }, };
export type BundleInput = { label: string, files: { [key in string]: string }, };
export type BundleCompressionMetrics = { compressedRetainedBytes: number, declaredRawBytes: number, chunksInflated: number, rawInflatedBytes: number, cacheHits: number, cachedRawBytes: number, };
export type PreparedExport = { label: string, cacheKey: string, artifactSha256: string, bytes: number, };
export type PreparedStageResult = { label: string, staged: number, artifactBytes: number, indexedMembers: number, decodeValidateMs: number, };
export type PrepareMountResult = { mounted: number, added: number, artifacts: Array<PreparedExport>, artifactBytes: number, preparedMembers: number, inputJsonBytes: number, base64Bytes: number, decodedSourceBytes: number, normalizedBytes: number, mountMemberBodyCopies: number, jsonParseMs: number, base64DecodeMs: number, normalizationMs: number, indexingMs: number, artifactEncodeMs: number, decodeValidatePrepareMs: number, mountMs: number, };
export type PackageMountResult = { mounted: number, added: number, packages: number, manifestJsonBytes: number, artifactBytes: number, retainedBlobBytes: number, indexedMembers: number, memberBodyCopies: number, manifestParseMs: number, decodeValidateMs: number, mountMs: number, compressedRetainedBytes: number, declaredRawBytes: number, chunksInflated: number, rawInflatedBytes: number, cacheHits: number, cachedRawBytes: number, };
export type ApiMessageError = { message: string, };
export type ApiSuccess<T> = { apiVersion: 1, ok: true, op: string, result: T, };
export type ApiFailure<E> = { apiVersion: 1, ok: false, op: string, error: E, };
export type ApiEnvelope<T, E> = ApiSuccess<T> | ApiFailure<E>;
export type Sha256Digest = string;
export type ContentRef = {
/**
 * The algorithm is fixed to SHA-256 and encoded in the field name.
 */
sha256: string, byteLength: number, mediaType?: string, };
export type BuildId = string;
export type SchemaVersion = "site-build/v2";
export type SourcePath = string;
export type SourceKind = { "kind": "fsh" } | { "kind": "config" } | { "kind": "predefined_resource" } | { "kind": "page" } | { "kind": "template" } | { "kind": "asset" } | { "kind": "other", name: string, };
export type SourceEntry = { kind: SourceKind, content: ContentRef, };
export type SourceManifest = { [key in string]: SourceEntry };
export type ProjectIdentity = { projectId: string,
/**
 * An SCM revision when available; otherwise a caller-defined immutable
 * revision label. Exact source hashes remain authoritative.
 */
revision: string, sources: SourceManifest, };
export type PackageCoordinate = string;
export type LockedPackage = { coordinate: PackageCoordinate,
/**
 * Exact deterministic prepared-package carrier. This content-addressed
 * value binds the complete package representation consumed by execution,
 * not merely its registry name/version or a normalized semantic subset.
 */
content: ContentRef, dependencies?: Array<PackageCoordinate>, };
export type PackageLock = { [key in string]: LockedPackage };
export type ProducerRef = { id: string, version: string, };
export type RenderMode = "native_template" | "external_builder";
export type RenderTarget = { renderer: ProducerRef, mode: RenderMode, fhirVersion: string, template?: PackageCoordinate, parameters?: { [key in string]: string }, };
export type ResourceKey = { resourceType: string, id: string, };
export type FragmentKind = { "kind": "narrative" } | { "kind": "summary" } | { "kind": "dictionary" } | { "kind": "terminology" } | { "kind": "table" } | { "kind": "other", name: string, };
export type FragmentScope = { "kind": "whole_ig" } | { "kind": "resource", resource: ResourceKey, };
export type AssetNamespace = { "kind": "authored" } | { "kind": "template" } | { "kind": "publisher_runtime" } | { "kind": "generated" } | { "kind": "other", name: string, };
export type ArtifactKey = { "kind": "semantic_model", name: string, } | { "kind": "resource", resource: ResourceKey, } | { "kind": "fragment", scope: FragmentScope, fragment: FragmentKind, parameters?: { [key in string]: string }, } | { "kind": "page", path: SourcePath, } | { "kind": "asset", namespace: AssetNamespace, path: SourcePath, } | { "kind": "data", namespace: string, name: string, };
export type ReadDependency = { "kind": "source", path: SourcePath, } | { "kind": "package", coordinate: PackageCoordinate, } | { "kind": "artifact", key: ArtifactKey, } | { "kind": "content", sha256: Sha256Digest, };
export type ArtifactProvenance = { producer: ProducerRef, recipe: string, attributes?: { [key in string]: string }, };
export type DiagnosticSeverity = "information" | "warning" | "error";
export type SourceLocation = { path: SourcePath,
/**
 * One-based, matching SUSHI's source line reporting.
 */
line: number,
/**
 * Zero-based, matching the parser/ANTLR column convention.
 */
column: number, };
export type BuildDiagnostic = {
/**
 * Stable producer-assigned emission order. Keeping it in the value preserves
 * meaningful diagnostic order while making collection insertion irrelevant.
 */
sequence: number, severity: DiagnosticSeverity, code: string, message: string, location?: SourceLocation, };
export type ArtifactState = { "status": "ready", content: ContentRef, } | { "status": "deferred", reason: string, } | { "status": "unsupported", capability: string, reason: string, } | { "status": "failed", diagnostics: Array<BuildDiagnostic>, };
export type ArtifactRecord = { key: ArtifactKey, state: ArtifactState, provenance: ArtifactProvenance, reads?: Array<ReadDependency>, };
export type ArtifactCatalog = Array<ArtifactRecord>;
export type RenderPlan = { requiredArtifacts: Array<ArtifactKey>, };
export type SiteBuild = { schemaVersion: SchemaVersion, buildId: BuildId, project: ProjectIdentity, packageLock: PackageLock, renderTarget: RenderTarget, renderPlan: RenderPlan, artifacts: ArtifactCatalog, diagnostics: Array<BuildDiagnostic>, };
export type ClosedSiteBuild = SiteBuild;
export type RendererImplementation = { id: string, version: string,
/**
 * Digest of the exact renderer code/assets/toolchain recipe used for this
 * invocation. Human version labels alone are not cache-safe.
 */
recipeSha256: string, };
export type OutputProducer = { id: string, version: string, };
export type SiteOutputFile = { path: string, content: ContentRef & { mediaType: string }, producer: OutputProducer, source?: string, owner?: string, };
export type SiteOutput = { schemaVersion: "site-output/v1", inputBuildId: string, renderer: RendererImplementation, outputSchema: string, options: { [key in string]: string }, files: Array<SiteOutputFile>, outputId: string, };
export type GeneratorSpec = { "generator": "cycle", buildEpochSecs: number, liquidAssetDirs: Array<string>, branch?: string | null, revision?: string | null, } | { "generator": "publisher", templateCoordinate: string, buildEpochSecs: number, activeTables: boolean, runUuid?: string | null, };
export type OutputResourceSubject = { resourceType: string, id: string, };
export type OutputSubjectPage = "primary" | "companion";
export type OutputKind = "page" | "asset" | "auxiliary";
export type OutputPageKind = "narrative" | "artifacts" | "profile" | "profile-companion" | "valueset" | "codesystem" | "example" | "toc" | "validation" | "generic";
export type OutputDescriptor = { path: string, kind: OutputKind, mediaType: string, content?: ContentRef, title?: string, subject?: OutputResourceSubject, subjectPage?: OutputSubjectPage, pageKind?: OutputPageKind, };
export type OutputCatalog = { buildId: string, outputs: Array<OutputDescriptor>, };
export type BuildStage = "wasm" | "manifest" | "project-cache-hit" | "project-verify" | "project-unpack" | "project-store" | "compile" | "snapshot" | "site-build" | "preview-publish" | "resolve" | "bundle-fetch" | "bundle-cache-hit" | "bundle-unpack" | "bundle-mount" | "registry-fetch" | "package-blocked" | "ready" | "lazy-fetch";
export type BuildEventSource = "window" | "worker" | "rust";
export type BuildEvent = {
/**
 * Functional operation when this observation belongs to an immutable
 * Build. Lifecycle/package/project-source events omit it.
 */
operation?: BuildOperation,
/**
 * Immutable build identity when one exists. Acquisition events that occur
 * before prepare establishes an identity omit it.
 */
buildId?: string,
/**
 * Stable machine-readable phase within the operation. `message` remains
 * presentation text and must not be parsed by benchmarks.
 */
phase?: string,
/**
 * Clock domain which measured this event. Browser hosts align Window and
 * Worker clocks through `performance.timeOrigin`; native hosts may omit it.
 */
source?: BuildEventSource,
/**
 * Unix-epoch milliseconds at the beginning of this measured span. This is
 * observational only and never participates in build identity.
 */
startMs?: number, stage: BuildStage, label?: string, bytes?: number, totalBytes?: number, message: string, fraction?: number, fromCache?: boolean, durationMs?: number, inputBytes?: number, outputBytes?: number, fileCount?: number, metrics?: { [key in string]: number }, };
export type BuildOperation = "lifecycle" | "prepare" | "outputs" | "render" | "finalize";
export type BuildErrorPhase = "lifecycle" | "input" | "package-resolution" | "package-transport" | "compilation" | "preparation" | "renderer" | "content-store" | "publication" | "finalization";
export type BuildErrorCode = "invalid-input" | "unavailable" | "integrity" | "resource-limit" | "compile-failed" | "renderer-failed" | "unknown-build" | "cancelled" | "internal";
export type BuildError<C> = { operation: BuildOperation, phase: BuildErrorPhase, code: BuildErrorCode, message: string, retryable: boolean, successfulCompilation?: C, };
